// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/business.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Business struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string                   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DisplayAddress       string                   `protobuf:"bytes,3,opt,name=display_address,json=displayAddress,proto3" json:"display_address,omitempty"`
	AddressDetails       *Business_AddressDetails `protobuf:"bytes,4,opt,name=address_details,json=addressDetails,proto3" json:"address_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Business) Reset()         { *m = Business{} }
func (m *Business) String() string { return proto.CompactTextString(m) }
func (*Business) ProtoMessage()    {}
func (*Business) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3f41d5571631870, []int{0}
}

func (m *Business) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Business.Unmarshal(m, b)
}
func (m *Business) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Business.Marshal(b, m, deterministic)
}
func (m *Business) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Business.Merge(m, src)
}
func (m *Business) XXX_Size() int {
	return xxx_messageInfo_Business.Size(m)
}
func (m *Business) XXX_DiscardUnknown() {
	xxx_messageInfo_Business.DiscardUnknown(m)
}

var xxx_messageInfo_Business proto.InternalMessageInfo

func (m *Business) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Business) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Business) GetDisplayAddress() string {
	if m != nil {
		return m.DisplayAddress
	}
	return ""
}

func (m *Business) GetAddressDetails() *Business_AddressDetails {
	if m != nil {
		return m.AddressDetails
	}
	return nil
}

type Business_AddressDetails struct {
	AddressLine_1        string   `protobuf:"bytes,1,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2        string   `protobuf:"bytes,2,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode           string   `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Business_AddressDetails) Reset()         { *m = Business_AddressDetails{} }
func (m *Business_AddressDetails) String() string { return proto.CompactTextString(m) }
func (*Business_AddressDetails) ProtoMessage()    {}
func (*Business_AddressDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3f41d5571631870, []int{0, 0}
}

func (m *Business_AddressDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Business_AddressDetails.Unmarshal(m, b)
}
func (m *Business_AddressDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Business_AddressDetails.Marshal(b, m, deterministic)
}
func (m *Business_AddressDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Business_AddressDetails.Merge(m, src)
}
func (m *Business_AddressDetails) XXX_Size() int {
	return xxx_messageInfo_Business_AddressDetails.Size(m)
}
func (m *Business_AddressDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_Business_AddressDetails.DiscardUnknown(m)
}

var xxx_messageInfo_Business_AddressDetails proto.InternalMessageInfo

func (m *Business_AddressDetails) GetAddressLine_1() string {
	if m != nil {
		return m.AddressLine_1
	}
	return ""
}

func (m *Business_AddressDetails) GetAddressLine_2() string {
	if m != nil {
		return m.AddressLine_2
	}
	return ""
}

func (m *Business_AddressDetails) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Business_AddressDetails) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Business_AddressDetails) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

type GetBusinessRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBusinessRequest) Reset()         { *m = GetBusinessRequest{} }
func (m *GetBusinessRequest) String() string { return proto.CompactTextString(m) }
func (*GetBusinessRequest) ProtoMessage()    {}
func (*GetBusinessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3f41d5571631870, []int{1}
}

func (m *GetBusinessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBusinessRequest.Unmarshal(m, b)
}
func (m *GetBusinessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBusinessRequest.Marshal(b, m, deterministic)
}
func (m *GetBusinessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBusinessRequest.Merge(m, src)
}
func (m *GetBusinessRequest) XXX_Size() int {
	return xxx_messageInfo_GetBusinessRequest.Size(m)
}
func (m *GetBusinessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBusinessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBusinessRequest proto.InternalMessageInfo

func (m *GetBusinessRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListBusinessesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBusinessesRequest) Reset()         { *m = ListBusinessesRequest{} }
func (m *ListBusinessesRequest) String() string { return proto.CompactTextString(m) }
func (*ListBusinessesRequest) ProtoMessage()    {}
func (*ListBusinessesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3f41d5571631870, []int{2}
}

func (m *ListBusinessesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBusinessesRequest.Unmarshal(m, b)
}
func (m *ListBusinessesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBusinessesRequest.Marshal(b, m, deterministic)
}
func (m *ListBusinessesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBusinessesRequest.Merge(m, src)
}
func (m *ListBusinessesRequest) XXX_Size() int {
	return xxx_messageInfo_ListBusinessesRequest.Size(m)
}
func (m *ListBusinessesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBusinessesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBusinessesRequest proto.InternalMessageInfo

type ListBusinessesResponse struct {
	Businesses           []*Business `protobuf:"bytes,1,rep,name=businesses,proto3" json:"businesses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListBusinessesResponse) Reset()         { *m = ListBusinessesResponse{} }
func (m *ListBusinessesResponse) String() string { return proto.CompactTextString(m) }
func (*ListBusinessesResponse) ProtoMessage()    {}
func (*ListBusinessesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3f41d5571631870, []int{3}
}

func (m *ListBusinessesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBusinessesResponse.Unmarshal(m, b)
}
func (m *ListBusinessesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBusinessesResponse.Marshal(b, m, deterministic)
}
func (m *ListBusinessesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBusinessesResponse.Merge(m, src)
}
func (m *ListBusinessesResponse) XXX_Size() int {
	return xxx_messageInfo_ListBusinessesResponse.Size(m)
}
func (m *ListBusinessesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBusinessesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBusinessesResponse proto.InternalMessageInfo

func (m *ListBusinessesResponse) GetBusinesses() []*Business {
	if m != nil {
		return m.Businesses
	}
	return nil
}

func init() {
	proto.RegisterType((*Business)(nil), "proto.Business")
	proto.RegisterType((*Business_AddressDetails)(nil), "proto.Business.AddressDetails")
	proto.RegisterType((*GetBusinessRequest)(nil), "proto.GetBusinessRequest")
	proto.RegisterType((*ListBusinessesRequest)(nil), "proto.ListBusinessesRequest")
	proto.RegisterType((*ListBusinessesResponse)(nil), "proto.ListBusinessesResponse")
}

func init() { proto.RegisterFile("proto/business.proto", fileDescriptor_b3f41d5571631870) }

var fileDescriptor_b3f41d5571631870 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0xca, 0xd3, 0x40,
	0x14, 0xc5, 0x49, 0xda, 0x8a, 0xdf, 0xcd, 0x67, 0x22, 0xd7, 0xaa, 0x31, 0x54, 0xad, 0xa1, 0x60,
	0x57, 0x0d, 0x8d, 0x4f, 0xe0, 0x1f, 0x28, 0x62, 0x71, 0x11, 0x37, 0xee, 0xc2, 0xb4, 0x73, 0x29,
	0x03, 0xe9, 0x4c, 0xec, 0x4c, 0x85, 0x22, 0x6e, 0x7c, 0x05, 0x1f, 0xc2, 0x57, 0xf0, 0x3d, 0x5c,
	0xb9, 0xf7, 0x41, 0xc4, 0xc9, 0xa4, 0xb6, 0xa9, 0xae, 0x92, 0x7b, 0xee, 0xef, 0x5c, 0xce, 0x19,
	0x18, 0xd6, 0x3b, 0x65, 0x54, 0xb6, 0xda, 0x6b, 0x21, 0x49, 0xeb, 0x99, 0x1d, 0x71, 0x60, 0x3f,
	0xc9, 0x68, 0xa3, 0xd4, 0xa6, 0xa2, 0x8c, 0xd5, 0x22, 0x63, 0x52, 0x2a, 0xc3, 0x8c, 0x50, 0xd2,
	0x41, 0xe9, 0x4f, 0x1f, 0x6e, 0xbe, 0x70, 0x3e, 0x0c, 0xc1, 0x17, 0x3c, 0xf6, 0xc6, 0xde, 0xf4,
	0xaa, 0xf0, 0x05, 0xc7, 0x27, 0x70, 0xcd, 0x85, 0xae, 0x2b, 0x76, 0x28, 0x25, 0xdb, 0x52, 0xec,
	0xdb, 0x4d, 0xe0, 0xb4, 0xb7, 0x6c, 0x4b, 0xf8, 0x14, 0xa2, 0x16, 0x61, 0x9c, 0xef, 0x48, 0xeb,
	0xb8, 0x67, 0xa9, 0xd0, 0xc9, 0xcf, 0x1b, 0x15, 0x17, 0x10, 0x39, 0xa0, 0xe4, 0x64, 0x98, 0xa8,
	0x74, 0xdc, 0x1f, 0x7b, 0xd3, 0x20, 0x7f, 0xd4, 0x24, 0x99, 0xb5, 0x29, 0x66, 0xce, 0xf1, 0xaa,
	0xa1, 0x8a, 0x90, 0x9d, 0xcd, 0xc9, 0x37, 0x0f, 0xc2, 0x73, 0x04, 0x27, 0xd0, 0x42, 0x65, 0x25,
	0x24, 0x95, 0x73, 0xd7, 0xe1, 0xda, 0xa9, 0x4b, 0x21, 0x69, 0x7e, 0x41, 0xe5, 0xae, 0xcf, 0x29,
	0x95, 0x23, 0x42, 0x7f, 0x2d, 0xcc, 0xc1, 0xb5, 0xb0, 0xff, 0x38, 0x84, 0x81, 0x36, 0xcc, 0x90,
	0x4d, 0x7c, 0x55, 0x34, 0x03, 0x3e, 0x86, 0xa0, 0x56, 0xda, 0xb0, 0xaa, 0x5c, 0x2b, 0x4e, 0xf1,
	0xc0, 0xee, 0xa0, 0x91, 0x5e, 0x2a, 0x4e, 0xe9, 0x04, 0x70, 0x41, 0xa6, 0xed, 0x55, 0xd0, 0x87,
	0x3d, 0x69, 0xd3, 0x7d, 0xe4, 0xf4, 0x3e, 0xdc, 0x5d, 0x0a, 0x7d, 0xc4, 0xa8, 0x05, 0xd3, 0xd7,
	0x70, 0xaf, 0xbb, 0xd0, 0xb5, 0x92, 0x9a, 0x30, 0x03, 0x58, 0x1d, 0xd5, 0xd8, 0x1b, 0xf7, 0xa6,
	0x41, 0x1e, 0x75, 0x9e, 0xb1, 0x38, 0x41, 0xf2, 0xef, 0x1e, 0x44, 0xed, 0xe2, 0x1d, 0xed, 0x3e,
	0x8a, 0x35, 0xe1, 0x1b, 0xe8, 0x2d, 0xc8, 0xe0, 0x03, 0xe7, 0xbb, 0x4c, 0x9a, 0x74, 0x4f, 0xa6,
	0xf1, 0x97, 0x1f, 0xbf, 0xbe, 0xfa, 0x88, 0xb7, 0xb3, 0xbf, 0xb7, 0xb3, 0x4f, 0x82, 0x7f, 0xc6,
	0xf7, 0xd0, 0xff, 0x93, 0x15, 0x47, 0xce, 0xf2, 0xcf, 0x46, 0xc9, 0xc3, 0xff, 0x6c, 0x9b, 0x5a,
	0xe9, 0x1d, 0x7b, 0xfe, 0x16, 0x06, 0x27, 0xe7, 0x57, 0x37, 0xac, 0xe5, 0xd9, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x34, 0x52, 0xf6, 0xd1, 0xe4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BusinessServiceClient is the client API for BusinessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessServiceClient interface {
	Get(ctx context.Context, in *GetBusinessRequest, opts ...grpc.CallOption) (*Business, error)
	List(ctx context.Context, in *ListBusinessesRequest, opts ...grpc.CallOption) (*ListBusinessesResponse, error)
}

type businessServiceClient struct {
	cc *grpc.ClientConn
}

func NewBusinessServiceClient(cc *grpc.ClientConn) BusinessServiceClient {
	return &businessServiceClient{cc}
}

func (c *businessServiceClient) Get(ctx context.Context, in *GetBusinessRequest, opts ...grpc.CallOption) (*Business, error) {
	out := new(Business)
	err := c.cc.Invoke(ctx, "/proto.BusinessService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceClient) List(ctx context.Context, in *ListBusinessesRequest, opts ...grpc.CallOption) (*ListBusinessesResponse, error) {
	out := new(ListBusinessesResponse)
	err := c.cc.Invoke(ctx, "/proto.BusinessService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServiceServer is the server API for BusinessService service.
type BusinessServiceServer interface {
	Get(context.Context, *GetBusinessRequest) (*Business, error)
	List(context.Context, *ListBusinessesRequest) (*ListBusinessesResponse, error)
}

// UnimplementedBusinessServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessServiceServer struct {
}

func (*UnimplementedBusinessServiceServer) Get(ctx context.Context, req *GetBusinessRequest) (*Business, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBusinessServiceServer) List(ctx context.Context, req *ListBusinessesRequest) (*ListBusinessesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterBusinessServiceServer(s *grpc.Server, srv BusinessServiceServer) {
	s.RegisterService(&_BusinessService_serviceDesc, srv)
}

func _BusinessService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusinessService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).Get(ctx, req.(*GetBusinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBusinessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BusinessService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceServer).List(ctx, req.(*ListBusinessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BusinessService",
	HandlerType: (*BusinessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _BusinessService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BusinessService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/business.proto",
}
